### ISSUE TITLE
ioUnit test overwrites expected output

### ISSUE THREAD

**Issue by barrettotte** [ioUnit/ioUnit#12]
ioUnit overwrites expected output causing it to fail on first test run. On a second run, the test will pass since the expected output has been overwritten.

<hr>

### First Run
**something.expected.json** =  ```[ ]```

Running a test for checking if **something.expected.json** is ```wasd```

**Result**: Test failed org.junit.ComparisonFailure: expected:<[wasd]> but was <[[ ]]>

<hr>

### Second Run
**something.expected.json** = ```wasd``` **Note:** This was not changed manually

Running the same test for checking if **something.expected.json** is ```wasd```

**Result**: Test passed

**Comment by ryaneberly** [comment]
iounit 0.6.0 contains this fix and published on maven
